title: Black Hawk Aviation
subtitle: Only the strong survive
email: info@blackhawkaviation.ca
description: >
  A rad aviation company  

owner: James Foster
phone: 1-306-380-5540

google_fonts : 
  primary: Oxygen
  secondary: Slabo 27px
  namespace: Oxygen|Slabo+27px
 
google_analytics : UA-73887811-8
# google_maps_api : AIzaSyADGT2nc6p6MAtPWw3U7tUsU-BDz6ls7CU

# other meta
color: '#e95c00'


###
### Probably shouldn't edit the settings below
###

# baseurl: "/blackhawkaviation" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page

gems:
  - jekyll-sitemap

markdown: kramdown
theme: minima

exclude: [
  'gulpfile.js',
  'package.json',
  'node_modules',
  'Gemfile*',
  'README.md',
  'LICENSE',
]
